### ISSUE TITLE
"This replay has no saved cursor data" error has occured to me a few times after editing a replay.

### ISSUE THREAD

**Issue by LordKamaYT** [thebetioplane/osuReplayEditorV3#62] opened 2023-07-02 17:01 UTC
The replay editor has the cursor data but not the exported replay

**Comment by thebetioplane** [comment] 2023-07-02 21:33
I think I just fixed this today, let me know if it works. BTW issue #54 covers this so I will close this as duplicate. If it didn't fix it let me know in #54 

Duplicate of  #54

**Closed by thebetioplane** 2023-07-02 21:33 UTC
